/*
 * ShowImage.java
 *
 * Created on December 5, 2008, 10:09 PM
 */
package stormr;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author  tom
 */
public class ShowImage extends javax.swing.JFrame
{

    Image image;

    /** Creates new form ShowImage */
    public ShowImage( Image i )
    {
        this.image = i;
        initComponents();
        setTitle( i.title );
        setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
        setSize( image.image.getWidth(), image.image.getHeight() );
        setVisible( true );
    }

    @Override
    public void paint( Graphics g )
    {
        g.drawImage( image.image, 0, 0, getWidth(), getHeight(), null );
        
        g.setColor( Color.pink );
        for (Image.Note note : image.notes)
        {
            g.drawRect( 
                    (int)note.location.getX() * getWidth() / image.image.getWidth(), 
                    (int)note.location.getY() * getHeight() / image.image.getHeight(), 
                    (int)note.location.getWidth() * getWidth() / image.image.getWidth(), 
                    (int)note.location.getHeight()* getHeight() / image.image.getHeight() );
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
